const limit_25_languages = [
  { value: "ar", name: "Arabic" },
  { value: "zh", name: "Chinese (Simplified)" },
  { value: "nl", name: "Dutch" },
  { value: "en", name: "English" },
  { value: "tl", name: "Filipino" },
  { value: "fr", name: "French" },
  { value: "de", name: "German" },
  { value: "el", name: "Greek" },
  { value: "iw", name: "Hebrew" },
  { value: "hi", name: "Hindi" },
  { value: "ga", name: "Irish" },
  { value: "it", name: "Italian" },
  { value: "ja", name: "Japanese" },
  { value: "ko", name: "Korean" },
  { value: "la", name: "Latin" },
  { value: "pl", name: "Polish" },
  { value: "pt", name: "Portuguese" },
  { value: "ru", name: "Russian" },
  { value: "es", name: "Spanish" },
  { value: "sv", name: "Swedish" },
  { value: "tr", name: "Turkish" },
  { value: "uk", name: "Ukrainian" },
  { value: "vi", name: "Vietnamese" },
  { value: "he", name: "Hebrew" },
];

const supportedLanguages = [
  { value: "af", name: "Afrikaans" },
  { value: "ak", name: "Akan" },
  { value: "sq", name: "Albanian" },
  { value: "am", name: "Amharic" },
  { value: "ar", name: "Arabic" },
  { value: "hy", name: "Armenian" },
  { value: "as", name: "Assamese" },
  { value: "ay", name: "Aymara" },
  { value: "az", name: "Azerbaijani" },
  { value: "bm", name: "Bambara" },
  { value: "eu", name: "Basque" },
  { value: "be", name: "Belarusian" },
  { value: "bn", name: "Bengali" },
  { value: "bho", name: "Bhojpuri" },
  { value: "bs", name: "Bosnian" },
  { value: "bg", name: "Bulgarian" },
  { value: "ca", name: "Catalan" },
  { value: "ceb", name: "Cebuano" },
  { value: "ny", name: "Chichewa" },
  { value: "zh", name: "Chinese (Simplified)" },
  { value: "zh-TW", name: "Chinese (Traditional)" },
  { value: "co", name: "Corsican" },
  { value: "hr", name: "Croatian" },
  { value: "cs", name: "Czech" },
  { value: "da", name: "Danish" },
  { value: "dv", name: "Divehi" },
  { value: "doi", name: "Dogri" },
  { value: "nl", name: "Dutch" },
  { value: "en", name: "English" },
  { value: "eo", name: "Esperanto" },
  { value: "et", name: "Estonian" },
  { value: "ee", name: "Ewe" },
  { value: "tl", name: "Filipino" },
  { value: "fi", name: "Finnish" },
  { value: "fr", name: "French" },
  { value: "fy", name: "Frisian" },
  { value: "gl", name: "Galician" },
  { value: "lg", name: "Ganda" },
  { value: "ka", name: "Georgian" },
  { value: "de", name: "German" },
  { value: "gom", name: "Goan Konkani" },
  { value: "el", name: "Greek" },
  { value: "gn", name: "Guarani" },
  { value: "gu", name: "Gujarati" },
  { value: "ht", name: "Haitian Creole" },
  { value: "ha", name: "Hausa" },
  { value: "haw", name: "Hawaiian" },
  { value: "iw", name: "Hebrew" },
  { value: "hi", name: "Hindi" },
  { value: "hmn", name: "Hmong" },
  { value: "hu", name: "Hungarian" },
  { value: "is", name: "Icelandic" },
  { value: "ig", name: "Igbo" },
  { value: "ilo", name: "Iloko" },
  { value: "id", name: "Indonesian" },
  { value: "ga", name: "Irish" },
  { value: "it", name: "Italian" },
  { value: "ja", name: "Japanese" },
  { value: "jw", name: "Javanese" },
  { value: "kn", name: "Kannada" },
  { value: "kk", name: "Kazakh" },
  { value: "km", name: "Khmer" },
  { value: "rw", name: "Kinyarwanda" },
  { value: "ko", name: "Korean" },
  { value: "kri", name: "Krio" },
  { value: "ku", name: "Kurdish (Kurmanji)" },
  { value: "ckb", name: "Kurdish (Sorani)" },
  { value: "ky", name: "Kyrgyz" },
  { value: "lo", name: "Lao" },
  { value: "la", name: "Latin" },
  { value: "lv", name: "Latvian" },
  { value: "ln", name: "Lingala" },
  { value: "lt", name: "Lithuanian" },
  { value: "lb", name: "Luxembourgish" },
  { value: "mk", name: "Macedonian" },
  { value: "mai", name: "Maithili" },
  { value: "mg", name: "Malagasy" },
  { value: "ms", name: "Malay" },
  { value: "ml", name: "Malayalam" },
  { value: "mt", name: "Maltese" },
  { value: "mni-Mtei", name: "Manipuri (Meitei Mayek)" },
  { value: "mi", name: "Maori" },
  { value: "mr", name: "Marathi" },
  { value: "lus", name: "Mizo" },
  { value: "mn", name: "Mongolian" },
  { value: "my", name: "Myanmar (Burmese)" },
  { value: "ne", name: "Nepali" },
  { value: "nso", name: "Northern Sotho" },
  { value: "no", name: "Norwegian" },
  { value: "or", name: "Odia (Oriya)" },
  { value: "om", name: "Oromo" },
  { value: "ps", name: "Pashto" },
  { value: "fa", name: "Persian" },
  { value: "pl", name: "Polish" },
  { value: "pt", name: "Portuguese" },
  { value: "pa", name: "Punjabi" },
  { value: "qu", name: "Quechua" },
  { value: "ro", name: "Romanian" },
  { value: "ru", name: "Russian" },
  { value: "sm", name: "Samoan" },
  { value: "sa", name: "Sanskrit" },
  { value: "gd", name: "Scots Gaelic" },
  { value: "sr", name: "Serbian" },
  { value: "st", name: "Sesotho" },
  { value: "sn", name: "Shona" },
  { value: "sd", name: "Sindhi" },
  { value: "si", name: "Sinhala" },
  { value: "sk", name: "Slovak" },
  { value: "sl", name: "Slovenian" },
  { value: "so", name: "Somali" },
  { value: "es", name: "Spanish" },
  { value: "su", name: "Sundanese" },
  { value: "sw", name: "Swahili" },
  { value: "sv", name: "Swedish" },
  { value: "tg", name: "Tajik" },
  { value: "ta", name: "Tamil" },
  { value: "tt", name: "Tatar" },
  { value: "te", name: "Telugu" },
  { value: "th", name: "Thai" },
  { value: "ti", name: "Tigrinya" },
  { value: "ts", name: "Tsonga" },
  { value: "tr", name: "Turkish" },
  { value: "tk", name: "Turkmen" },
  { value: "uk", name: "Ukrainian" },
  { value: "ur", name: "Urdu" },
  { value: "ug", name: "Uyghur" },
  { value: "uz", name: "Uzbek" },
  { value: "vi", name: "Vietnamese" },
  { value: "cy", name: "Welsh" },
  { value: "xh", name: "Xhosa" },
  { value: "yi", name: "Yiddish" },
  { value: "yo", name: "Yoruba" },
  { value: "zu", name: "Zulu" },
  { value: "he", name: "Hebrew" },
  { value: "jv", name: "Javanese" },
  { value: "zh-CN", name: "Chinese (Simplified)" },
];

module.exports = { supportedLanguages, limit_25_languages };
